2019-10-05 11:04:29,893 : kivy : Factory: 194 symbols loaded
2019-10-05 11:04:29,985 : kivy : Image: Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-10-05 11:04:30,016 : kivy : VideoGstplayer: Using Gstreamer 1.10.2.0
2019-10-05 11:04:30,016 : kivy : Video: Provider: gstplayer
2019-10-05 11:04:30,043 : kivy : Loading MPF-MC controller
2019-10-05 11:04:30,044 : mpfmc : Mission Pinball Framework Media Controller v0.52.5
2019-10-05 11:04:30,044 : mpfmc : Mission Pinball Framework Game Engine v0.52.7
2019-10-05 11:04:30,044 : mpfmc : Machine path: /Users/brianevans/Projects/HeistMPF
2019-10-05 11:04:30,045 : ConfigProcessor : Config file in cache changed: /Users/brianevans/Projects/HeistMPF/config/config
2019-10-05 11:04:30,045 : ConfigProcessor : Loading config from file /Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpfmc/mcconfig.yaml.
2019-10-05 11:04:30,091 : ConfigProcessor : Loading config: /Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpfmc/mcconfig.yaml
2019-10-05 11:04:30,105 : ConfigProcessor : Loading config from file /Users/brianevans/Projects/HeistMPF/config/config.
2019-10-05 11:04:30,137 : kivy : Error found in file /Users/brianevans/Projects/HeistMPF/config/config.yaml: 'Key "p" was defined multiple times in config   in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 14, column 5'
Traceback (most recent call last):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 198, in load
    config = self.process(f)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 114, in construct_document
    for dummy in generator:
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "p" was defined multiple times in config   in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 14, column 5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpfmc/commands/mc.py", line 209, in __init__
    thread_stopper=thread_stopper).run()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpfmc/core/mc.py", line 97, in __init__
    self.machine_config = self._load_config()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpfmc/core/mc.py", line 223, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file /Users/brianevans/Projects/HeistMPF/config/config.yaml: 'Key "p" was defined multiple times in config   in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 14, column 5'
2019-10-05 11:04:30,140 : kivy : Stopping child threads... (0 remaining)
2019-10-05 11:04:30,140 : kivy : All child threads stopped.
